version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash

env:
  variables:
    "testEnv" : "testValue1"
    
steps:
  - type: Command
    name: "Test oci cli with access"
    timeoutInSeconds: 400
    command: |
      echo "Have access"
      PATH=$PATH:/test
      echo $PATH
      vi abc.txt
      oci os object put --bucket-name testBucket --file abc.txt
